### ISSUE TITLE
can't parse go if statements in expressions

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#120]
Minimal example:
```
> sgrep -lang go -e "if (true)" README.md
Fatal error: exception (Failure "fail to parse pattern: 'if (true)' in lang go")
> sgrep -lang go -e "if (true) { ... } " README.md
Fatal error: exception (Failure "fail to parse pattern: 'if (true) { ... } ' in lang go")
```

**Comment by aryx** [comment]
you can't specify half statement (or half expression).
I need to parse the pattern, so right now I look for an 'expr' or 'stmt' or 'stmt stmt' or 'decl' but not for a 'if_header'

**Comment by aryx** [comment]
Note that Go imposes to use {} around the then and else parts of an if
so you currently need to use that too

**Comment by aryx** [comment]
ah, forgot to read completely your message.

**Comment by aryx** [comment]
The if (true) { ... } should now work with the latest pfff.

**Comment by aryx** [comment]
introduce regressions in sgrep tests actually. Reopening.
