### ISSUE TITLE
python function call subtleties

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#144]
https://github.com/returntocorp/sgrep-rules/blob/663a95579bb825f578068794ffc63c41cb9e3417/python/socket/bind.py#L24

```
    - pattern-either:
        - pattern: |
            $S = socket.socket(...)
            ...
            $S.bind(("0.0.0.0", ...))
        - pattern: |
            $S = socket.socket(...)
            ...
            $S.bind(("", ...))
```
is triggering on:
```
easy_s = socket.socket(doesnt, matter)
easy_s.bind()
```

But I expect it not to, given it has no arguments.

**Comment by aryx** [comment]
Is it normal there is extra parenthesis inside $S.bind? (("", ...))

**Comment by ievans** [comment]
Yes, not a typo -- you call `.bind` with a tuple

**Comment by aryx** [comment]
I can't reproduce on your test example.
If I do this pattern:
$S = socket.socket(...)
...
$S.bind()

$  /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -f tests/python/misc_tuple.sgrep tests/python/
/home/pad/github/sgrep/tests/python/misc_tuple.py:1
 easy_s = socket.socket(doesnt, matter)
 easy_s.bind()

it finds it. But I put back your pattern:
$S = socket.socket(...)
...
$S.bind(("", ...))

$ /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -f tests/python/misc_tuple.sgrep tests/python/
then no match (as expected).
