### ISSUE TITLE
pipe error messages to stderr

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#154]
sgrep-core should pipe output to stderr especially when outputting json/r2c mode, these issues should be collected under the `errors` key

using latest sgrep-lint with the --config=r2c option on 

```
git clone https://github.com/yaml/pyyaml /tmp/pyyaml && cd /tmp/pyyaml && git checkout 5986257f9fc978d4a61b6e0001df554f80e565cb && cd -
```
The following is output to stdout, but it should really go to stderr:

PB: Ast_c_build, on /analysis/inputs/public/source-code/ext/_yaml.h (exn = (Failure "/analysis/inputs/public/source-code/ext/_yaml.h:23:0: no ifdef"))

Full reference, see failure at https://dev.massive.ret2.co/jobs/544?page=1&sort_on=repo_url&sort_by=asc

**Comment by aryx** [comment]
I can't reproduce either, or maybe I misunderstood.
But for me the error does go on stderr.

$ yy -lang c -e 'XXXXX' -r2c .
+ /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -lang c -e XXXXX -r2c .
(ONCE) skipping: #if PY_MAJOR_VERSION < 3

(ONCE) skipping: #ifdef _MSC_VER	
PB: Ast_c_build, on /tmp/pyyaml/ext/_yaml.h (exn = (Failure "/tmp/pyyaml/ext/_yaml.h:23:0: no ifdef"))
{ "results": [] }
pad@yrax:/tmp/pyyaml$ yy -lang c -e 'XXXXX' -r2c . > /tmp/res
+ /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -lang c -e XXXXX -r2c .
(ONCE) skipping: #if PY_MAJOR_VERSION < 3

(ONCE) skipping: #ifdef _MSC_VER	
PB: Ast_c_build, on /tmp/pyyaml/ext/_yaml.h (exn = (Failure "/tmp/pyyaml/ext/_yaml.h:23:0: no ifdef"))
pad@yrax:/tmp/pyyaml$ cat /tmp/res 
{ "results": [] }
