### ISSUE TITLE
unfriendly error if the input directory is empty

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#164]
If `find` doesn't find anything, it will return 1 and we will throw a confusing error to the user inside sgrep core.

```
/ # sgrep -lang python -rules_file /analyzer/data/basic.yml /analysis/inputs/public/source-code
Fatal error: exception Common.CmdError(_, "CMD = find  '/analysis/inputs/public/source-code' -type f | grep -v /.hg/ |grep -v /CVS/ | grep -v /.git/ |grep -v /_darcs/| grep -v /.svn/ | grep -v .git_annot | grep -v .marshall, RESULT = ")
```

Desired behavior: don't raise an exception if there are no files returned

**Comment by aryx** [comment]
I can fix that.

I currently filter files under .hg, _darcs, .git, etc. but I would rather delegating this job to something else (sgrep.py, or bento). Can I? Should I?
