### ISSUE TITLE
... in function body doesn't appear to handle no other statements

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#186]
```sgrep
for $KEY, $VALUE in $DICT.items():
    ...
    del $DICT[$KEY]
```

does not match

```python

for k,v in d.items():
    del d[v]

```

See https://github.com/returntocorp/sgrep-rules/pull/144/files I worked around by having two patterns one with `...` and the other without

**Comment by aryx** [comment]
Well you want d[k] in your concrete example, not d[v], otherwise it will not match indeed.
But yes, there was a bug, see the diff.
