### ISSUE TITLE
Using function declaration parameters in a pattern

### ISSUE THREAD

**Issue by brendongo** [returntocorp/sgrep#201]
**Describe the bug**
I am having trouble writing rules that reference parameters in sgrep.

## 1

**Code**
```
def func(a,b=[]):
    print(b)
```

**Pattern**
```
def $F(...,$D=[]):
    ...
    print($D)
```

## 2

**Code**
```
def func(a,b=[]):
    b.append(1)
```

**Pattern**
```
def $F(...,$D=[]):
    ...
    $D.append(...)
```

**Comment by aryx** [comment]
should work now with develop

**Comment by brendongo** [comment]
Thanks for the quick turn around @aryx!
