### ISSUE TITLE
error running under pre-commit: no space left on device

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#205]
**Describe the bug**

When running sgrep locally under `pre-commit run --all`, I get the following output:
```
hookid: sgrep-develop

[Errno 28] No space left on device: '/tmp/aHR0cHM6Ly9naXRodWIuY29tL3JldHVybnRvY29ycC9zZ3JlcC1ydWxlcy90YXJiYWxsL21hc3Rlcg=='
No config given. If you want to see some examples, try running with --config r2c
```

**Comment by aryx** [comment]
Does pre-commit limits the size of /tmp? I think I do create a few temporary files
in sgrep, mostly to parse the patterns.

**Comment by DrewDennison** [comment]
I don’t think this is a pre-commit problem. Pre-commit should do do a dumb Docker run. This seems like a Docker out of disk space error. Feel free to edit .pre-commit-config.yaml and remove the sgrep hook if it’s blocking you.

**Comment by ievans** [comment]
Confirmed this is a docker out of space error, fixed with `docker system prune`
