### ISSUE TITLE
_ in metavariable names appears to be supported but does not work

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#211]
I expect that `$X` and `$X_Y` are both identifiers for a single metavariable, but this is not true in practice.
```
ine@imbp4 ~/D/r/test-repos [2]> time sgrep-lint --strict --lang py -e '$X == $X' libcloud/
libcloud/libcloud/compute/drivers/cloudsigma.py
615:        node = [node for node in nodes if node.id == node.id]
ine@imbp4 ~/D/r/test-repos> time sgrep-lint --strict --lang py -e '$X_IS_COOL == $X_IS_COOL' libcloud/
```

We should either update the documentation or change metavar parsing.

**Comment by aryx** [comment]
This was done for PHP a long time ago. PHP uses $XXX (as well as Ruby) so
I've restricted a metavar to just a single letter (that's still 26 metavars you can use in one pattern),
which means you would not be able to match PHP vars using a single uppercase letter, but
this is rare I think.

**Comment by ievans** [comment]
@aryx and I discussed; you can in fact use as many uppercase letters as you want, but `_` or `-` do not work, which is expected. We need to update documentation to reflect.
