### ISSUE TITLE
bug with identifier equality (seen in eqeq check)

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#22]
See for instance https://app.r2c.dev/triager/triage?analyzer_name=beta/sgrep&analyzer_version=0.1.16&commit=499faf4eb9f9ccf0b21dc728e974970f54bd6c52&selected_regions=%5B%7B%22rows%22%3A%5B0%2C0%5D%7D%5D

This is a false positive when it comes to the identifiers that appears to originate inside sgrep/pfff core.

**Comment by aryx** [comment]
That's bad, that's very bad!

**Comment by daghan** [comment]
Here is another instance, slightly different variant

`myList[a] = value
myList[a] = foo(myList)`

https://dev.massive.ret2.co/triager/triage/534/68148?check_ids=sgrep-rules.python.deadcode.useless-assignment-keyed&selected_regions=%5B%7B%22rows%22%3A%5B0%2C0%5D%7D%5D

**Comment by aryx** [comment]
No, this one is different, it's a problem in your rule, not in sgrep. The first issue reported by isaac
is a bug in sgrep itself, it should not report that inword == outword with the $X == $X rule.

**Comment by aryx** [comment]
link does not work anymore.
Anyway I think it should be fixed now.
