### ISSUE TITLE
Support detection of unbroken infinite loops

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#223]
**Is your feature request related to a problem? Please describe.**
A user today tried to test our rule set by writing the following code into a Python file:

```python
while True:
   pass
```

I can write an sgrep pattern like so:
```yaml
-pattern: |
    while True:
        ...
-pattern-not: |
    while True:
        ...
        break
        ...
-pattern-not: |
    while True:
        ...
        return
        ...
```

However, we'll still fire on code like
```python
while True:
   if some_condition:
       return
   pass
```

Theoretically, I can cover all single-nesting cases by enumerating every possible combination of Python conditional and jump statements, but this still would leave doubly and higher-nested jump statements.
   

**Describe the solution you'd like**
Any concise solution in `sgrep-lint` to filter out patterns with arbitrary nesting.

**Comment by ievans** [comment]
@nbrahms with the deep statement matching support, are you unblocked on this?

**Comment by nbrahms** [comment]
@ievans I updated to latest sgrep, and the posted pattern doesn't work yet.

Is there documentation on how to use the deep statement matching support?

**Comment by ievans** [comment]
@nbrahms are you sure you're using the latest version? https://sgrep.live/Q4x

**Comment by nbrahms** [comment]
Hi @ievans ... Using the latest version, I still seem to get a false positive:

https://github.com/returntocorp/sgrep-rules/blob/nathan/while-true/python/smells/while-true.py

**Comment by ievans** [comment]
https://sgrep.live/34l - it looks like we should file a bug for deep stmts not going into `try` blocks

**Comment by aryx** [comment]
This does not work? Should work now no?

**Comment by nbrahms** [comment]
@aryx Confirmed fixed!
