### ISSUE TITLE
sgrep does not parse anonymous JavaScript functions

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep#226]
**Describe the bug**
sgrep does not parse anonymous JavaScript functions

**To Reproduce**
See https://sgrep.live/2KB
Copied here for preservation:

sgrep pattern:
```javascript
function() {
    ...
}
```

JavaScript test case:
```
var foo = "bar"

function () {
    console.log(foo)
}
```

Error:
```
in /home/repo/.sgrep.yml, pattern in rule pattern_id can't be parsed for language js: function() {
...
}
1 invalid patterns found inside rules; aborting
```

**Comment by aryx** [comment]
Is this valid JS code? You can have a toplevel anonymous function?
how do you call it then if it's not even assigned anywhere?

**Comment by inkz** [comment]
@aryx 
You absolutely right, this is a dead code, I did not investigate the case enough before submitting it, as I see now it is possible to catch usages of anonymous functions in common cases
https://sgrep.live/boQ
https://sgrep.live/NxA

My point was to claim for opportunity to find code pattern inside an anonymous function without specifying the exact scenario

something like this: https://sgrep.live/kWe

**Comment by inkz** [comment]
BTW does `sgrep` support arrow functions?

**Comment by minusworld** [comment]
> BTW does `sgrep` support arrow functions?

I would assume that it doesn't at the moment, given that I haven't heard about it.  Hopefully soon!
