### ISSUE TITLE
Sgrep pattern fails to parse for java class

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/sgrep#238]
**Describe the bug**
Pattern: 
```
class A {
  ...
} 
```

**To Reproduce**
1. Run 
```
ulziibayarotgonbaatar@ulziibayars-MacBook-Pro sgrep % ./_build/default/bin/main_sgrep.exe -verbose -f tests/java/less_inheritance.TODO -lang java tests/java/less_inheritance.java.TODO
Fatal error: exception (Failure
   "fail to parse pattern: 'class A {\
  \n  ...\
  \n}' in lang java (exn = Parsing.Parse_error)")
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aryx** [comment]
I guess this is done! Good job ulzii.
