### ISSUE TITLE
Sgrep does not understand that python functions can be in any order

### ISSUE THREAD

**Issue by brendongo** [returntocorp/sgrep#241]
**Is your feature request related to a problem? Please describe.**
When using the pattern 
```
 class $C:
                def $A(..., $D=[], ...):
                    ...
                    self.$E = $D
                def $B(...):
                    ...
                    self.$E.append(...)
```
sgrep fails to find instances when B is declared before A, or other functions are declared between A and B.

See https://sgrep.live/pGJ

**Describe the solution you'd like**
Ideally sgrep handles all possible cases of function declaration (even inheritance).

**Comment by brendongo** [comment]
It looks like this also fails if there is another function declared before A and B

**Comment by DrewDennison** [comment]
@brendongo does and extra `...` take care of your comment above? https://sgrep.live/2LB

**Comment by DrewDennison** [comment]
Agreed this is still a bug though

**Comment by brendongo** [comment]
the ... solves if there are functions declared before A but then B still has to directly folllow A.

**Comment by DrewDennison** [comment]
you can hack around it with another `...` https://sgrep.live/X2w

**Comment by aryx** [comment]
You can currently hack it by using multiple patterns with pattern-and in the yaml file (suboptimal solution).

**Comment by aryx** [comment]
Non trivial to implement given the way the sgrep core engine work. Not a first-time-user task.

**Comment by aryx** [comment]
It works now!
