### ISSUE TITLE
finding nested expressions inside other patterns

### ISSUE THREAD

**Issue by jtmelton** [returntocorp/sgrep#255]
**Describe the bug**
In the Java language, I would like to detect the case where we have an assignment `if(x = true)` instead of a comparison `if(x == true)`. However when I write the rule for '$X = $Y', it doesn't do what I want. It produces more results, including assignment statements (`this.name = name;`). 

**To Reproduce**
1. run the command `docker run --rm -v $(pwd):/home/repo returntocorp/sgrep -e '$X = $Y' --lang java .`

**Expected behavior**
It should return only findings that are in an if block. I attempted to change the command to `if('$X = $Y)` but it was an invalid rule. It may be that this is not a bug, but rather me not understanding how to write the rule I want. 

**Desktop (please complete the following information):**
 - OS: [os x]
 - Version [latest docker]

**Additional context**
 It may very well be that this is not a bug, but rather me not understanding how to write the rule I want.

**Comment by ievans** [comment]
Hi @jtmelton, welcome and thanks for opening an issue! If I understand you correctly, you'd like to find code of the type:

```
if (x = true) { 
   // do something
}
```

For that, you should be able to use this pattern:
```
if ($X = true) { ... }
```
I built a full example here: https://sgrep.live/3xG

The reason your previous attempt failed is that `if ($X = $Y)` is invalid as an expression is that sgrep can't operate on a half-expression or half-statement (https://github.com/returntocorp/sgrep/blob/develop/docs/patterns.md#you-can-not-use-a-half-expression-or-half-statement-pattern)

**Comment by jtmelton** [comment]
Hi, that's exactly what I want to get to. I updated the example with a few more patterns that I had in a local test to show places where it's not caught. https://sgrep.live/4xL

**Comment by jtmelton** [comment]
Note the difference when I run these files locally ... 

```$ docker run --rm -v $(pwd):/home/repo returntocorp/sgrep -e '$X = $Y' --lang java .
HelloWorld.java
7:		if(s = false) {
14:		if(s = true || 1 == 1) {
16:		} else if(1 == 2 || (s = true)) {
18:		} else if(1 == 3 && (s = false || 1 == 4)) {
$ docker run --rm -v $(pwd):/home/repo returntocorp/sgrep -e 'if ($X = true) { ... }' --lang java .

$ ``` 

and the source file for testing ... 
```$ cat -n HelloWorld.java 
     1	package abc;
     2	
     3	public class HelloWorld
     4	{
     5		public static void main(String[] args) {
     6			boolean s = true;
     7			if(s = false) {
     8				int i1 = "555";
     9				System.err.println("assignment");
    10			}
    11			if(s == false) {
    12				System.err.println("compare");
    13			}
    14			if(s = true || 1 == 1) {
    15				System.err.println("a1");
    16			} else if(1 == 2 || (s = true)) {
    17				System.err.println("a2");
    18			} else if(1 == 3 && (s = false || 1 == 4)) {
    19				System.err.println("a3");
    20			} 
    21	
    22			System.out.println("Hello World!");
    23		}
    24	}
$```

**Comment by ievans** [comment]
@jtmelton thanks for the clarification and the updated live example! There are a couple different ways to approach what you want, but they are feature requests rather than currently supported features. 

For instance, you could use the ... operator to catch the rest of the operators in the expression, but this would only match assignments as the first expression in the `if`:
if ($X = 1 ...) { ... }

An expansion could be to allow this syntax to indicate that it doesn't matter where the expression lives:
if (... $X = 1 ...) { ... }

What are your thoughts? We have tickets tracking this CFG-awareness as part of more general features like #229.

**Comment by jtmelton** [comment]
Yeah, I think that makes sense to me. I initially tried to write the expression as `if (... $X = 1 ...)` actually. I also think this rule could be further improved by adding type info as I saw in the presentation pdf, ie. `if (... $X = bool ...)` or `if (... $X = bool:true ...)` would be great. I like the expansion concept for this, as it feels to fit into the rest of the model. 

By the way, _very_ cool project in general. I've wanted to build something like this for a long time, but y'all did it way better than I would have. Really excited to see where the project goes. (h/t to Clint Gibler for pointing it out to me)

**Comment by DrewDennison** [comment]
@jtmelton thanks for opening the issues. I'm the dev behind https://sgrep.live and I would love any feedback you have about it. To the extent you're getting different results, that's a bug. https://sgrep.live/PJ3 looks ok to me but I'll dig in more around the differences between single rules and the full boolean composition.

**Comment by DrewDennison** [comment]
@clintgibler 🎩

**Comment by jtmelton** [comment]
Very good - thanks @DrewDennison fantastic work! As you may have noticed, I've not really pushed the system to its' limits :>. Having said that, I'll try to come up with some more rules over the next few days and let you know if I find anything interesting.

**Comment by aryx** [comment]
Yes I'm not sure about the syntax we should use to express what you want.
We could have if(x = true) implicitely match if(stuff && (x= true)) but I'm not sure that's
what we always want. Some other users may want to match conditionals where we just test
for x = true.
The if (... x = true ...) is an idea, but until now '...' has been used to express sequence of stuff, here
it's not really a sequence but more the idea of a nested expression. I think Coccinelle use the if(<... x = true ...>) syntax, but it's not great either.

**Comment by clintgibler** [comment]
@jtmelton Nice, glad you like it! And thanks for the detailed test cases. 

@DrewDennison https://sgrep.live is super useful! 🥇 

## Thoughts on Intended Behavior

+1 @aryx, I'm still thinking about what should be intended behavior here. 

Initial hot take: if the user provides an explicit expression (e.g. `if (x = true)` then that is matched directly, and you need to be clear if you want to match more general cases (e.g. `if (... x = true ...)` ).
* *Pros*: what is matched is explicit and clear (potentially easier for users to reason about sgrep's behavior (as there's no additional magical mapping happening in the background), assuming you understand how sgrep works.
* *Cons*: new users / people without some experience or intuition about how sgrep works may initially not be able to match what they're looking for.

-----

The following probably isn't the best place to put these, but placing them here for now, as they related to @jtmelton's thread.

## **Feature request**: Helpful error message when invalid pattern supplied

I had a similar issue to @jtmelton in that some of my first sgrep search patterns were fragments and thus were not parsed by sgrep. It would be nice to have some error message when parsing fails that gives common failure reasons and examples of proper search terms. 

If sgrep could detect what the user is trying to do and give specific advice, e.g. `$FOO(` => "Hey it looks like you're trying to match a function call, try `$FOO(...)`", that would be 🚀 

But for now, having a generic error message that gives examples of how to do each common pattern should be sufficient (e.g. assignments, function calls, function definitions, conditionals, maybe a handful of others).

## Feature request: Allow specifying types

Per @jtmelton's [comment above](https://github.com/returntocorp/sgrep/issues/255#issuecomment-595442919), it'd be nice to specify types for what you're matching.

Not sure how best to have users specify this.

For already typed languages, maybe sgrep could use existing syntax:

~~~java
// java
int x = $VAL;

public static void $FOO(int $VAR, ...) { ... }
~~~

For dynamically typed languages, sgrep should be able to handle some simple cases without doing fancy type inference, just using the AST, e.g. for constants.

~~~python
# python

# I believe this is currently supported
$X = "..." # X is any hard coded string
exec("...", ...) # first arg to exec is hard coded string
~~~

After a bit more poking, it looks like this is currently supported for ints/floats as well:

~~~yaml
# https://github.com/returntocorp/sgrep-rules/blob/develop/python/smells/sleep.yaml
rules:
  - id: arbitrary-sleep
    patterns:
      - pattern-not: time.sleep($F(...))
      - pattern-either:
        - pattern: |
             time.sleep($X: int)
        - pattern: |
             time.sleep($X: float)
    message: "time.sleep() call; did you mean to leave this in?"
    languages: [python]
    severity: ERROR
~~~

~~~python
# https://github.com/returntocorp/sgrep-rules/blob/develop/python/smells/sleep.py

# ruleid:arbitrary-sleep
t.sleep(5)
# ruleid:arbitrary-sleep
t.sleep(0.1)
# todoruleid:arbitrary-sleep
time.sleep("bad")
~~~

## Questions
For @aryx (or others)
* What is the current set of types that can be matched? Any Python primitive or only specific ones?
* Can this be done in any language or just for Python?

Also, note that [patterns.md](https://github.com/returntocorp/sgrep/blob/develop/docs/patterns.md#string-matching) describes matching hard coded strings but not int or float constants.

**Comment by aryx** [comment]
For @clintgibler 
- Currently the typed metavariables ($X: <type>) are only used to match literals. Actually we should
not use $X: int but really $X: int_literal, that would be more correct. 
- Right now there is just for Python. It could be added to the other language but we need to find a syntax for it in the other languages that do not conflicts with other constructs (and does not introduce any conflicts in the grammar of the language). I'm opened to suggestions for syntax. I think it makes sense to reuse the typing syntax of the host language, but then it's not always possible to use that syntax in an expression context.

**Comment by clintgibler** [comment]
@aryx OK great, thanks for the info. Hm, good point re: having an sgrep type syntax that doesn't interfere with the host language.

Would this work?
* In cases where types can be specified reusing syntax of the host language, sgrep does that.
* In cases where that's not possible, for example, in an expression context, sgrep supports an additional `pattern` clause, like `pattern-type` or `pattern-metavar-type`, that allows the user to say: "this metavar should have this type."

Here's an example, based on @jtmelton's work above (https://sgrep.live/4xL):

~~~yaml
rules:
  - id: assignment-comparison
    patterns:
      - pattern: if ($X = $Y) { ... }
      - pattern-metavar-type:
        "$Y": "bool_literal" 
    message: "The value of `$X` is being ignored and will be used in the conditional test"
    languages: [java]
    severity: ERROR
~~~ 

This may not be the best approach, just the first one that came to mind. It seems like this approach could work, if metavars were enforced to be the same across each pattern (#176).

**Comment by aryx** [comment]
This works now! 
Right now there is no need for special syntax, if (x = true) will implicitely be tried on nested
expressions inside the if (e.g., it will match if (a && x = true)).
We can revisit later this decision and choose whether we want people to write instead if (... x = true ...) if the feedback on this feature (called deep expression matching) is bad.


For the related discussions in this thread, @clintgibler please create separate issues to track them.

**Comment by clintgibler** [comment]
Done: #308 and #309 ^
