### ISSUE TITLE
sgrep research phase 1

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#28]

**Comment by dan5382** [comment]
Research resulted in an understanding of our internal sgrep process. 
We believe we can make sgrep better by concentrating on the local experience and making it super fast to iterate. 

We understand the next set of work now: 
- 1 sgrep panel in Bento website
- * Will default to platform with results tab open
- * Might spend a couple cycles thinking through Triager and Platform to merge the two.

Extra credit will be: 
An sgrep landing page idea (not needed now but might be nice)
