### ISSUE TITLE
Support matching of JSX attributes

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#282]
I want to match this expression in JSX:

```jsx
<div dangerouslySetInnerHTML="something bad" />
```

Ideally, I'd be able to write a pattern like:
```
<div ... dangerouslySetInnerHTML=... />
```
in `sgrep` to match it. I use the `...` inside the tag to match any combination of attributes. The order of attributes should never matter.

I'm ok having to write two patterns; once for self-closing elements (`<div />`), and another for enclosing elements (`<div>...</div>`).

**Comment by aryx** [comment]
You don't need '...', it does not care about other attributes by default.
Also you just need one pattern, it handles the different variations you mentioned.

**Comment by nbrahms** [comment]
👍 @aryx
