### ISSUE TITLE
Improve Docker PWD volume mount for "Run Locally"

### ISSUE THREAD

**Issue by bburky** [returntocorp/sgrep#287]
When clicking "Run Locally" on sgrep.live `$(pwd)` is used unquoted in the `docker run` command. This will expand to multiple arguments incorrectly if PWD contains spaces. Use quotes like `-v "$(pwd):/home/repo"` to address this.

Additionally, you could just use the environment variable `PWD` avaliable in (all?) shells. That is, use `-v "${PWD}:/home/repo"`. As a bonus, this is valid PowerShell syntax unlike `$(pwd)` and improves usage on Windows.

An example of the full new command could be:

```
docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config=https://sgrep.live/c/ASDF
```

**Comment by DrewDennison** [comment]
@bburky thanks for the issue. I'll definitely make the change to `"${PWD}:/home/repo"`
