### ISSUE TITLE
Python decorator support

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#29]
desired:

code:
```
@alpha @beta @charlie('xyz')
def foo():
    x = 42
```

should be matched by these patterns:
```
@alpha
def (...):
    ...
```

```
@charlie(...)
def (...):
    ...
```

```
@charlie("xyz")
def (...):
    ...
```

**Comment by aryx** [comment]
I don't think we need the @..., 
just @charlie("xys") def(...): ... should match

**Comment by aryx** [comment]
It's one of the core principle of sgrep I don't have a good name for; I used to call it 
"isomorphism by absence" or "less-is-ok", but it just says that you don't have to give all the details
in the pattern; For example the absence of decorator in the pattern will also match code using decorators, or writing int x;  will also match static int x;
Do you have a name for this principle?

**Comment by ievans** [comment]
@aryx I agree with you on reflection, I don't have a name for the principle though. I will update the issue to reflect!

**Comment by ulziibay** [comment]
Decorator support for the last item in 
" accessing g request.form, request.json, request.data outside POST/PUT/DELETE handler"
https://github.com/returntocorp/sgrep-rules/issues/5 is needed. Would be great addition to sgrep python

**Comment by ievans** [comment]
Confirmed working, thank you! Added https://github.com/returntocorp/sgrep-rules/pull/29 to regression test as well.
