### ISSUE TITLE
"Match anything" (...) inside javascript objects

### ISSUE THREAD

**Issue by inkz** [returntocorp/sgrep#297]
It would be effective if there was a possibility to use `...` inside an object
https://sgrep.live/O8b

rule:
```
var $F = {
    ...,
    two: 2
};
```
example:
```javascript
var foo = {
    one: 1,
    two: 2,
}
```

**Comment by aryx** [comment]
Maybe there is no need to use '...'?

**Comment by aryx** [comment]
Inside fields, we should maybe automatically assume you want to match things in any order
and you don't need to specify everything?

**Comment by inkz** [comment]
if this
```
test({one: 1});
```
matches this
```javascript
test({one: 1, two: 2})
```
(which looks intuitive to me)
then there is no need in `...`  :+1:

**Comment by aryx** [comment]
yes, this works now.

**Comment by aryx** [comment]
closing for now, we can revisit later if the decision to not require '...' was good.

**Comment by inkz** [comment]
awesome!

**Comment by inkz** [comment]
single pattern works fine: https://sgrep.live/krK
```
var $X = {one: 1}
```

but if I wrap it into the rule it fails
https://sgrep.live/w30

```yaml
rules:
  - id: test
    pattern: var $X = {one: 1};
    message: "yo"
    languages: [javascript]
    severity: ERROR
```

```
in .sgrep.yml, pattern in rule pattern_id can't be parsed for language js: rules:
- id: test
pattern: var $X = {one: 1};
message: "yo"
languages: [javascript]
severity: ERROR
1 invalid patterns found inside rules; aborting
```

next thing is that pattern seems to catch only the first property of the object:
https://sgrep.live/krK

```
var $X = {one: 1};
```

```javascript
var x = {
    one: 1,
    two: 2,
    three: 3
}
```

but this will return no results:
https://sgrep.live/xqp

```
var $X = {two: 2};
```

```javascript
var x = {
    one: 1,
    two: 2,
    three: 3
}
```
