### ISSUE TITLE
sgrep inside bento.dev

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep#3]
Snazzy-looking sgrep landing page at bento.dev that explains the steps to write and run your own rule.

**Comment by dan5382** [comment]
@ievans for this ticket the check boxes don't match what we need to do. Based on the content of this we are talking about Sgrep user flows (within product). 

While the topic is Sgrep landing page. Can we change this so it matches? I dont mind changing myself just didn't want to blow away anyones work.

**Comment by ievans** [comment]
Yes, I think the title is correct and the checkboxes are wrong. Fire away!
