### ISSUE TITLE
sgrep.live bug report

### ISSUE THREAD

**Issue by mschwager** [returntocorp/sgrep#323]
https://sgrep.live/1zD

Here's the original example code textarea:

![2020-03-20-130600_1398x401_scrot](https://user-images.githubusercontent.com/1724818/77197899-99c50800-6aab-11ea-931b-50d3557832fe.png)

I then used the "expander" in the bottom right to drag the area larger so I could see more code:

![2020-03-20-130255_1388x587_scrot](https://user-images.githubusercontent.com/1724818/77197714-49e64100-6aab-11ea-8fcc-afa3eaf53ba8.png)

The problem is it still limits the amount of code in view. As you can see above, it cuts off part of line 16 and all the code after, despite there being plenty of space. If we scroll down further we can see there are additional lines:

![2020-03-20-130311_1386x580_scrot](https://user-images.githubusercontent.com/1724818/77197830-75692b80-6aab-11ea-94d9-9ce9d9d15033.png)

It be great to be able to fit more lines of code on larger screens, and fix this "expander" bug.

**Comment by DrewDennison** [comment]
thanks @mschwager I'll get this fixed asap

**Comment by DrewDennison** [comment]
This should be fixed now on https://sgrep.live please re-open if you still see issues
