### ISSUE TITLE
[Python] Support matching of f-strings

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#326]
**Is your feature request related to a problem? Please describe.**
I'd like to match on Python f-strings.

For example, I'd like to detect when an unsafe local variable is reflected into a Flask response using an f-string.

**Describe the solution you'd like**
Match using something like:
```python
f"...{$X}..."
```

**Describe alternatives you've considered**
Python explodes this pattern into:

```python
"..." + str($X) + ...
```

so a match on ^^ would work as well.

**Additional context**
See https://sgrep.live/EyA

**Comment by ulziibay** [comment]
@aryx I am going to claim this. I look forward to your CR!

**Comment by ulziibay** [comment]
@nbrahms actually, if you look at https://sgrep.live/rN1  the 
```
f"...{$X}..."
```
can already match a lot of the cases. NOTE THAT `...` means more than 0 in this case.
I am working on the false positives found in this pattern!

**Comment by nbrahms** [comment]
oh hmmm

**Comment by nbrahms** [comment]
Good catch @ulziibay 🙇 . Looks like we can close?

**Comment by brendongo** [comment]
For reference this is working https://sgrep.live/eG8
