### ISSUE TITLE
Return unique + deterministic metavariable identifier with match

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#328]
**Is your feature request related to a problem? Please describe.**
In order to use `sgrep` for certain applications (e.g. comparing results from two patterns, or asserting that one pattern occurs "inside" another pattern), we would like `sgrep` to return a unique identifier for each match.

For example:

If

```python
@flask.route("...")
def action($X):
   ...
```

```python
unsafe_expression($X)
```

both match some code, I'd like to be able to assert that the match to `$X` in each pattern is the same metavariable.

**Describe the solution you'd like**
For each metavariable, return an identifier for each match, that obeys the following properties:
- For variable matches, it will be the same for the same symbol in the same scope
- The chance that the identifier will be the same for two different matches within a file has a small upper bound

It would also be nice if the following property held:
- The identifier does not change between two runs of `sgrep` on the same program

**Describe alternatives you've considered**
Note that many, but not all, use cases can be accomplished via deep statement match. However, this creates two problems:
- This doesn't work when matching expressions within a deep statement match
- The lines returned by a deep statement match are overly broad

**Comment by aryx** [comment]
Note that for "For variable matches, it will be the same for the same symbol in the same scope" it means we need to correctly handle scope for all the languages, and try to do in a generic way; not trivial. Each programming language has its own scoping rules, and even some commercial IDEs still do not handle correctly scope and have scoping bugs during refactoring.

**Comment by aryx** [comment]
What to do if the metavariable matches a complex expression? What should sgrep-core return?
Right now sgrep-core returns for each match the metavariable bindings as a buggy string. It could return the AST as a string (as shown by the AST dumper), like "$X" => "Call(Int 1, [Int 2])" or do you also want to associate an id with that?

**Comment by nbrahms** [comment]
> Note that for "For variable matches, it will be the same for the same symbol in the same scope" it means we need to correctly handle scope for all the languages, and try to do in a generic way; not trivial. Each programming language has its own scoping rules, and even some commercial IDEs still do not handle correctly scope and have scoping bugs during refactoring.

I think it's ok to not be 100% accurate.

As an acceptance criterion, let's imagine the following two patterns (in Python):

```
def foo($X):
   ...
```

and 

```
return $X
```

In this example:

```
def foo(x):
   return x
```

both patterns should return the same ID.

In this example:

```
def foo(x):
   return 1

def bar(x):
   return x
```

the metavariable should belong to two different scopes.

IMO we can probably punt on things like shadowing, globals, etc. for now.

**Comment by nbrahms** [comment]
> What to do if the metavariable matches a complex expression? What should sgrep-core return?
> Right now sgrep-core returns for each match the metavariable bindings as a buggy string. It could return the AST as a string (as shown by the AST dumper), like "$X" => "Call(Int 1, [Int 2])" or do you also want to associate an id with that?

As a first-order solution, can we say anything that's not either a constant literal or declared variable has an effectively unique identifier?

**Comment by aryx** [comment]
I could return the sha1 of the AST when converted to a string.

**Comment by nbrahms** [comment]
> I could return the sha1 of the AST when converted to a string.

I assume the nodes have some sort of unique ID that would cause the complex nodes to have different values?

Multiple call expressions in non-strictly functional languages aren't guaranteed to yield the same result, alas, so we wouldn't want them to match.

**Comment by aryx** [comment]
I'm not sure I understand what you mean.

The nodes in the AST do not have a unique ID, only variables in different scopes will have a different unique ID.
in foo(f(1), f(1)) the AST for the two f(1) are mostly identical (they do not have the same line information, but sgrep internally removes sometimes those line information so when you do foo($X, $X) we just compare if the AST are structurally equal.

What I was suggesting is that when $X matches a variable, I return the unique ID of the scope of the variable, and otherwise the sha1 of the AST (so above, the sha1 of the two f(1) will be identical).

**Comment by nbrahms** [comment]
If we do that, I think we need to also add a "type" tag to the metavariables to indicate when we're matching a variable vs. a parent AST node.

**Comment by aryx** [comment]
no, the LHS in many languages can be an array access, or pointer access, or now even a pattern (a tuple, a partial list, a record/object, etc.)

**Comment by aryx** [comment]
This should work now (we just need to update the tests in sgrep_lint).
Next step is to leverage the information in sgrep_lint.
