### ISSUE TITLE
Add support for user-defined equivalences

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#329]
**Is your feature request related to a problem? Please describe.**
We may want to the user to be able to define equivalences that can be used for pattern reuse.

As a motivating example, let's consider possible ways to iterate over a list in Python:

```python
for el in list:
   ...
```
```python
it = (... for el in list)
for x in it:
   ...
```
```python
for ix in range(len(list)):
   el = list[ix]
   ...
```
```python
for _, el in enumerate(list):
   ...
```

A user may want to write multiple patterns dominated by this list iteration. It would be useful to support this.

**Describe the solution you'd like**
I think there are many options here, but it might be nice to have some way of specifying a template.

E.g., in the example above:

```python
%%ITER<$X,$Y>%%
   ...
```

could match `el` and `list` in any of the examples above, and a YAML file could define the equivalence classes.

**Comment by DrewDennison** [comment]
Sounds like it wouldn't be too hard to do in the python wrapper

**Comment by aryx** [comment]
Yes, great idea.

**Comment by aryx** [comment]
Here is the config file we had in coccinelle for C "isomorphhisms" (code equivalences)

https://github.com/coccinelle/coccinelle/blob/master/standard.iso

**Comment by aryx** [comment]
I'll close for now. We can create another ticket for alternative solutions or new features on the current solution.
