### ISSUE TITLE
Follow variables usage inside functions and classes (js)

### ISSUE THREAD

**Issue by inkz** [returntocorp/sgrep#336]
trying to catch usage of a var like this:

```yaml
var $X = 1;
...
console.log($X);
```
examples:
https://sgrep.live/BGx
https://sgrep.live/DAd
https://sgrep.live/WjL
https://sgrep.live/0GB
https://sgrep.live/KgL

```javascript
var x = 1;

function foo() {
    console.log(x);
}
```

```javascript
var x = 1;

foo(() => {
    console.log(x);
})
```

```javascript
var x = 1;

foo(function() {
    bar(() => {
        console.log(x);
    })
})
```

```javascript
const x = 1;

class Hello {
    
	test() {
		console.log(x);
	}
    
}
```

```javascript
var x = 1;

function OldSchool () {
    
    this.test = function() {
        console.log(x);
    }
    
}
```

**Comment by aryx** [comment]
Yes right now the deep statement does not go through function definitions. It does not go through function boundaries. My thought was it would be slow, and that I would need first to handle scope correctly (a function can reuse the same variable name of an enclosing variable).

**Comment by aryx** [comment]
So this is blocked on https://github.com/returntocorp/sgrep/issues/328 anyway.

**Comment by aryx** [comment]
This can now be solved either by having a really really deep stmt matching where
 ... flatten and include also the statements inside functions/classes/lambdas/etc.
This may be slow, I don't know.

Or this can be solved by using 2 patterns now that we correctly resolve names and tag variables, but this will require to modify sgrep-lint to leverage the new information provided by issue #328 (the unique_id field for metavars).

**Comment by aryx** [comment]
Should work now with the really deep stmt matching
