### ISSUE TITLE
Switch to generic name resolution

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#351]
@aryx to fill in details

**Comment by aryx** [comment]
sgrep was originally using a Python-specific name resolver and alias resolver to manage renamed imports in Python. Later on, sgrep was using a Go-specific name resolver for Go. However each of those resolvers had lots of code duplication and was incomplete in different ways. This was not scalable as we add more languages to sgrep. In past diffs I've started a generic name resolver to factorize the code but it was still working side-by-side with the pl-specific resolvers. However both resolvers were conflicting sometimes and this introduced many regressions in sgrep and sgrep-rules. After the diff above, we use just the generic name resolver and implemented enough in it to not regress on Go and Python.
