### ISSUE TITLE
Make sgrep compatible with ubuntu:16.04

### ISSUE THREAD

**Issue by brendongo** [returntocorp/sgrep#352]
Currently the sgrep binary along with the sgrep-lint executable are built on ubuntu:18.04. This causes compatibility issues on 16.04 primarily because of libc versions.

**Comment by aryx** [comment]
In theory we could build sgrep-core as a static binary.
See https://github.com/ocaml/ocaml/issues/9131#issuecomment-556354099 which recently got "fixed".

**Comment by brendongo** [comment]
https://github.com/returntocorp/sgrep/pull/343 and https://github.com/returntocorp/sgrep/pull/366

@aryx Yeah definitely thinking of linking using musl or something.
