### ISSUE TITLE
Publish `sgrep` to Homebrew

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#371]
This is done when:
- [x] Update the brew tap to build the release from source
- [x] `brew install sgrep` installs a runnable binary version of sgrep
- [x] We have a documented build process for releasing new versions

**Comment by rcoh** [comment]
Current threshold is 70 stars & also not a fork:
```      new_formula_problem "GitHub fork (not canonical repository)" if metadata["fork"]
      if (metadata["forks_count"] < 30) && (metadata["subscribers_count"] < 30) &&
         (metadata["stargazers_count"] < 75)
        new_formula_problem "GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)"
      end

      return if Date.parse(metadata["created_at"]) <= (Date.today - 30)

      new_formula_problem "GitHub repository too new (<30 days old)"
```
But I will make you a tap

**Comment by aryx** [comment]
Actually sgrep is already taken by another project. I don't remember what were the options we were discussing to rename sgrep in something else. I think @dlukeomalley might remember.

**Comment by aryx** [comment]
returntocorp/sgrep was extracted from returntocorp/pfff (an umbrella project), which was moved from facebookarchive/pfff, which used to be facebook/pfff, which had lots of stars. I don't know if we can "transfer" those stars.

**Comment by nbrahms** [comment]
https://www.cs.helsinki.fi/u/jjaakkol/sgrep.html

**Comment by nbrahms** [comment]
@pabloest @dlukeomalley I know there was a proposal to rename to `sg` (i.e. "sounds good"), not sure if that had a fanbase.

Also not sure if brew has a minimum character count.

**Comment by pabloest** [comment]
@nbrahms There were a few possibilities discussed and documented [here](https://returntocorp.quip.com/dVIfAK4TWE4m/sgrep-package-naming).

There’s no clear winner but the leading contenders seem to be `brew install sg` and `brew cask install sgrep`. Neither get around the issue of people running `brew install sgrep` because they think that’s the way to go. It already happened once to one of our users.

Ideally the package name, domain name, and CLI command are all the same.

**Comment by nbrahms** [comment]
> @nbrahms There were a few possibilities discussed and documented [here](https://returntocorp.quip.com/dVIfAK4TWE4m/sgrep-package-naming).
> 
> There’s no clear winner but the leading contenders seem to be `brew install sg` and `brew cask install sgrep`. Neither get around the issue of people running `brew install sgrep` because they think that’s the way to go. It already happened once to one of our users.
> 
> Ideally the package name, domain name, and CLI command are all the same.

I'm actually advocating for changing the name of our linting tool altogether, away from `sgrep`
