### ISSUE TITLE
ParseError on .c and .h files

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#389]
sgrep go rules fail on https://github.com/daghan/invoicer-chapter2

```PB: Ast_c_build, on /github/workspace/vendor/golang.org/x/crypto/otr/libotr_test_helper.c (exn = (Failure hd))
sgrep: /github/workspace/vendor/golang.org/x/crypto/otr/libotr_test_helper.c: FatalError
sgrep: /github/workspace/vendor/github.com/mattn/go-sqlite3/sqlite3ext.h: ParseError
sgrep: /github/workspace/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.h: ParseError
sgrep: NO FILE INFO YET: LexicalError```

**Comment by DrewDennison** [comment]
@ievans yeah but given that his is @daghan 's hello world learning project we can expect similar results from users of go checks

**Comment by daghan** [comment]
Is this an issue with my project setup? Should I figure out a way to exclude those vendor libs?

**Comment by DrewDennison** [comment]
no that's standard in go

**Comment by DrewDennison** [comment]
I'm surprised sgrep is picking up `.c` and `.h` files when lang is `go`

**Comment by aryx** [comment]
What was the command you ran? I don't see how sgrep -lang go can give error in C files.

**Comment by aryx** [comment]
I've fixed -exclude-dir, so you should be able to exclude the vendor directory.

Regarding the parse error in .c and .h files, this is quite normal. The C parser in sgrep uses heuristics to parse C code before preprocessing (see https://github.com/returntocorp/sgrep/issues/448 for more information) and so sometimes it fails. I've added another command line option, -macros, to specify a file containing macro to partially expand, which can help (this is what we were doing in coccinelle, and this is what I do in my other tools such as codemap/codegraph/scheck/...).

**Comment by aryx** [comment]
Closing. Let me know if you still have the problem.
