### ISSUE TITLE
better class matching

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#50]
the pattern:

```
class A(...)
```

should match 
```
class A:
class A():
class A(ParentClass):
```

**Comment by aryx** [comment]
I've also allowed class A:  to match class definitions with parents (less-is-ok spirit, like
for attributes where a pattern for a function not specifying any attribute will also match function definitions using attributes.
This is debatable. In any case the (...) should work, but it's very Python specific for now.
