### ISSUE TITLE
ocaml error running rules with `return $X`

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#52]
**Describe the bug**
`Fatal error: exception (Failure "empty list, max_min_ii_by_pos")`

**To Reproduce**
1. `sgrep-lint --no-rewrite-rule-ids -f python/smells/return-in-init.yaml python/smells/return-in-init.py` from https://github.com/returntocorp/sgrep-rules/pull/12

**Expected behavior**
Not an ocaml exception :)

**Comment by aryx** [comment]
I think this should work now.
