### ISSUE TITLE
command to validate a pattern

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#6]
It would be helpful to have an sgrep command that validates whether a pattern can be parsed for a particular language flag. For instance, this could be used in a repl to indicate to the user whether the pattern is valid at every keystroke.

**Comment by aryx** [comment]
What is the interface you want? where is the pattern stored? in the yaml file? on the command-line?
on stdin?

**Comment by ievans** [comment]
Just the command line I think, i.e.: 

```
sgrep --validate-pattern="$X =\ def()" -> return 1
sgrep --validate-pattern="$X == $X" -> return 0
```

**Comment by aryx** [comment]
You'll need to handle patterns on multiple lines

**Comment by ievans** [comment]
@aryx could I embed newlines eg: "def $X():\n..." or does sgrep treat them specially?

**Comment by aryx** [comment]
you'll need to call me with a string containing real newlines, not "\n" that I have to interpret.
This is why maybe reading from stdin or from a file is simpler. There are always weird things
the shell is doing with arguments interpretation, removing quotes, interpreting $, etc.

**Comment by ievans** [comment]
How about stdin then?

```
cat my-pattern.sgrep | sgrep --validate-pattern-stdin
echo $?  # returns 0 if valid or 1 if invalid
```
