### ISSUE TITLE
python identifier not matched when imported

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#74]
Hey @aryx 

I was trying to match

```
metrics.send(f"{function}.success", 'counter', '1', metric_tags={"source": source})
``` 

and I wrote 

```
metrics.send(...)
```

and 

```
metrics.send($X, 'counter', '...', ...)

```

But I got no matches

line is from https://github.com/Netflix/lemur/commit/d2c7330fb7e5956b67fce2d98340473dd7f6ce5e

cc @daghan

**Comment by ievans** [comment]
This is expected behavior, because earlier in celery.py:

`from lemur.extensions import metrics, sentry`

so the correct pattern is: `lemur.extensions.metrics.send(...)`

**Comment by aryx** [comment]
We could also report those cases, or warn the user that maybe they should qualifiy more
in the sgrep pattern.
