### ISSUE TITLE
consecutive statements not matched (javascript and python)

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#92]
See https://github.com/returntocorp/sgrep-rules/pull/44

expect that:
```
            $X = $Y;
            $X = $Z;
```
will match:
```
var x = 1;
x = 2;
x = 3;
```
But it does not.

**Comment by aryx** [comment]
Can't reproduce for python at least.

**Comment by aryx** [comment]
+ /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -f tests/python/misc_stmts1.sgrep tests/python/
/home/pad/github/sgrep/tests/python/equivalence_naming_import.py:11
     result = subprocess.open("ls")
     # ERROR:
     result = sub_open("ls")
     # ERROR:
     result = sub.open("ls")
 
     result = sub.not_open("ls")
/home/pad/github/sgrep/tests/python/misc_stmts1.py:2
   x = 1
   x = 2
   x = 3

**Comment by ievans** [comment]
@aryx For python: ```
cd /tmp/test
curl https://raw.githubusercontent.com/returntocorp/sgrep-rules/70a61d508ac8fa6abc8b300c6ddcba9e7c8fa3d5/python/deadcode/useless-assign.yaml > .sgrep.yml
curl https://raw.githubusercontent.com/returntocorp/sgrep-rules/70a61d508ac8fa6abc8b300c6ddcba9e7c8fa3d5/python/deadcode/useless-assign.py > useless-assign.py
docker run --rm -v (pwd):/home/repo returntocorp/sgrep:develop
```
Outputs:
```
running 2 rules from 1 yaml files (0 yaml files were invalid)
useless-assign.py:6 useless-assignment-keyed - key `i` in `d` is assigned twice; the first assignment is useless
```
So rule `useless-assignment` should fire but does not.

```
 ✖ FAILED file: javascript/deadcode/useless-assign.yaml check: useless-assignment
 ✖ FAILED file: python/deadcode/useless-assign.yaml check: useless-assignment
```
